---
- name: Install docker
  gather_facts: No
  hosts: default

  tasks:
    - name: Restart a container
      docker_container:
        name: myapplication
        image: someuser/appimage
        state: started
        restart: yes
        links:
         - "myredis:aliasedredis"
        devices:
         - "/dev/sda:/dev/xvda:rwm"
        ports:
         - "8080:9000"
         - "127.0.0.1:8081:9001/udp"
        env:
            SECRET_KEY: "ssssh"
            # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
            BOOLEAN_KEY: "yes"