---
- name: Quandoo
  gather_facts: No
  hosts: default

  tasks:
   - name: set SSH_KEY_ENV
     environment:
       SSH_KEY_ENV: whatever_value 
      
  - name: Build Docker image from Dockerfile
    docker_image:
      name: appimage
      path: container1/
      state: build
      
  - name: Get pub key from container 1
    shell: docker exec container1 cat /home/docker_root/.ssh/id_rsa.pub
    register: ssh_key_gen

  - name: set SSH_KEY_ENV_GEN
    environment:
    SSH_KEY_ENV_GEN: ssh_key_gen 
 
   - name: Build Docker image from Dockerfile
     docker_image:
       name: appimage
       path: container2/
       state: build
      
  - name: Running the container
    docker_container:
      name: container1
      image: appimage
      state: running

  - name: Running the container
        docker_container:
          name: container2
          image: appimage
          state: running
          links:
           - "container1:container1"
  
  - name: Test connection
    shell: docker exec container1 ssh docker_root@container2



