---
- name: Quandoo
  gather_facts: No
  hosts: default

  tasks:
  - name: Running the container
    docker_container:
      name: container1
      image: someuser/appimage
      state: running

  - name: Running the container
        docker_container:
          name: container2
          image: someuser/appimage
          state: running
          links:
           - "container1:container1"
          env:
              SECRET_KEY: "ssssh"
              # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
              BOOLEAN_KEY: "yes"





