---
- name: Quandoo
  gather_facts: No
  hosts: default

  tasks:
   - name: Echo SSH_KEY_ENV
     shell: "echo $SSH_KEY_ENV"
     environment:
      SSH_KEY_ENV: whatever_value 
      
  - name: Build Docker image from Dockerfile
    docker_image:
      name: appimage
      state: build
 
  - name: Running the container
    docker_container:
      name: container1
      image: appimage
      state: running

  - name: Running the container
        docker_container:
          name: container2
          image: appimage
          state: running
          links:
           - "container1:container1"
          env:
              SECRET_KEY: "ssssh"
              # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
              BOOLEAN_KEY: "yes"





